//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_UsersInRoles
    {
        public int PkID { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> UserEntryID { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<System.DateTime> UserEffectedDate { get; set; }
    
        public virtual aspnet_Roles aspnet_Roles { get; set; }
    }
}
