//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstBusinessType
    {
        public int id { get; set; }
        public string BusinessType { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<System.DateTime> UserEffectedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
