//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstBankMaster
    {
        public MstBankMaster()
        {
            this.tblMstUserBankDetails = new HashSet<tblMstUserBankDetail>();
        }
    
        public int Id { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<System.DateTime> UserEffectedDate { get; set; }
        public Nullable<int> UserEntryId { get; set; }
    
        public virtual ICollection<tblMstUserBankDetail> tblMstUserBankDetails { get; set; }
    }
}
