//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstLanguage
    {
        public MstLanguage()
        {
            this.tblMstUserMasters = new HashSet<tblMstUserMaster>();
        }
    
        public int Id { get; set; }
        public string LanguageName { get; set; }
        public string LanguageCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<tblMstUserMaster> tblMstUserMasters { get; set; }
    }
}
