//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstMenuMaster
    {
        public MstMenuMaster()
        {
            this.MstMenuRoleMasters = new HashSet<MstMenuRoleMaster>();
        }
    
        public int MenuId { get; set; }
        public string MenuText { get; set; }
        public string MenuDesc { get; set; }
        public string NavigateURL { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> UserEntryID { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<System.DateTime> UserAffectedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<MstMenuRoleMaster> MstMenuRoleMasters { get; set; }
    }
}
