//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MstUserWorkCategory
    {
        public MstUserWorkCategory()
        {
            this.tblMstUserCategoryMappings = new HashSet<tblMstUserCategoryMapping>();
        }
    
        public int Id { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
        public Nullable<decimal> CategoryPrice { get; set; }
        public Nullable<int> CatIntroPercentage { get; set; }
        public Nullable<int> CatWorkPercentage { get; set; }
        public Nullable<int> WorkPaymentRate { get; set; }
        public Nullable<int> UserEntryId { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<System.DateTime> UserEffectedDate { get; set; }
    
        public virtual ICollection<tblMstUserCategoryMapping> tblMstUserCategoryMappings { get; set; }
    }
}
