//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstUserMaster
    {
        public tblMstUserMaster()
        {
            this.tblMstUserCategoryMappings = new HashSet<tblMstUserCategoryMapping>();
            this.tblMstUserDetails = new HashSet<tblMstUserDetail>();
            this.tblMstUserTreeStructures = new HashSet<tblMstUserTreeStructure>();
        }
    
        public int UserId { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> UserEntryId { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<System.DateTime> UserEffectedDate { get; set; }
        public Nullable<bool> AcceptTermCondition { get; set; }
    
        public virtual MstLanguage MstLanguage { get; set; }
        public virtual ICollection<tblMstUserCategoryMapping> tblMstUserCategoryMappings { get; set; }
        public virtual ICollection<tblMstUserDetail> tblMstUserDetails { get; set; }
        public virtual ICollection<tblMstUserTreeStructure> tblMstUserTreeStructures { get; set; }
    }
}
