//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstUserCategoryMapping
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
    
        public virtual MstUserWorkCategory MstUserWorkCategory { get; set; }
        public virtual tblMstUserMaster tblMstUserMaster { get; set; }
    }
}
