//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstUserDetail
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public string AlteranateContact { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<bool> IsWelcomeMailSend { get; set; }
        public Nullable<bool> IsMemberShipTaken { get; set; }
        public Nullable<bool> IsMemberShipExpired { get; set; }
        public Nullable<int> UserType { get; set; }
        public Nullable<int> PersonalIdType { get; set; }
        public string PersonalIdNo { get; set; }
        public string UserImage { get; set; }
        public string CurrentAddress { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CityId { get; set; }
        public string RegisterRefrelCode { get; set; }
        public string SelfRefrelCode { get; set; }
        public Nullable<System.DateTime> LastPaymentDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UserEntryId { get; set; }
    
        public virtual MstCity MstCity { get; set; }
        public virtual tblMstUserMaster tblMstUserMaster { get; set; }
    }
}
