//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstUserPaymentDetail
    {
        public int PaymentID { get; set; }
        public string TransitionID { get; set; }
        public int UserID { get; set; }
        public decimal PaidAmount { get; set; }
        public bool IsGstInvoice { get; set; }
        public Nullable<int> GstNumber { get; set; }
        public string GstHolderName { get; set; }
        public string GstHolderAddress { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual tblMstUserMaster tblMstUserMaster { get; set; }
    }
}
