//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effigy.Entity.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniqueURLAudit
    {
        public int Id { get; set; }
        public Nullable<int> UniqueURLId { get; set; }
        public string UniqueURL { get; set; }
        public Nullable<int> URLStatus { get; set; }
        public Nullable<bool> IsAddressExist { get; set; }
        public Nullable<bool> IsCityExist { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<bool> IsStateExist { get; set; }
        public Nullable<bool> IsCountryExist { get; set; }
        public Nullable<bool> IsProfileExist { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public Nullable<int> ProductImageCount { get; set; }
        public Nullable<int> ProductDescCount { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserEntryId { get; set; }
        public Nullable<System.DateTime> UserEntryDate { get; set; }
        public Nullable<System.DateTime> UserEffectedDate { get; set; }
    }
}
